/** Showcase images (server screenshots) shared by the dashboard and the landing page. */
export const SHOWCASE_IMAGES: string[] = [
  '0.avif',
  '1.avif',
  '2.avif',
  '3.avif',
  '4.avif',
  '5.avif',
  '6.avif',
  '7.avif',
  '8.gif',
  '9.avif',
  '10.avif',
  '11.avif',
  '13.avif',
  '14.avif',
  '15.avif',
  '16.avif',
  '17.avif',
  '18.avif',
  '19.avif',
  '20.avif',
  '21.avif',
  '22.avif',
  '23.gif',
  '24.avif',
];
