// AUTO-GENERATED by tools/generate-ui-registry.mjs — do not edit manually.
// Regenerates automatically before every build/serve (see package.json pre-hooks).

import type { UiComponentMeta } from './registry';

import { BadgeComponent } from './badge/badge.component';
import * as badgeDemo from './badge/badge.demo';
import { ButtonComponent } from './button/button.component';
import * as buttonDemo from './button/button.demo';
import { CardComponent } from './card/card.component';
import * as cardDemo from './card/card.demo';
import { DialogComponent } from './dialog/dialog.component';
import * as dialogDemo from './dialog/dialog.demo';
import { FormFieldComponent } from './input/form-field.component';
import * as formFieldDemo from './input/form-field.demo';
import { InputComponent } from './input/input.component';
import * as inputDemo from './input/input.demo';
import { ProgressComponent } from './progress/progress.component';
import * as progressDemo from './progress/progress.demo';
import { SpinnerComponent } from './spinner/spinner.component';
import * as spinnerDemo from './spinner/spinner.demo';

export const UI_REGISTRY: UiComponentMeta[] = [
  {
    name: 'BadgeComponent',
    selector: 'ui-badge',
    description: 'Small status badge with color variants; exposes data-variant on the host element.',
    inputs: [{ name: 'variant', type: 'UiBadgeVariant', default: 'neutral', required: false }],
    outputs: [],
    component: BadgeComponent,
    demos: badgeDemo.demos,
  },
  {
    name: 'ButtonComponent',
    selector: 'ui-button',
    description: 'Button with color variants, four sizes, full-width mode and an inline loading spinner.',
    inputs: [
      { name: 'variant', type: 'UiButtonVariant', default: 'primary', required: false },
      { name: 'size', type: 'UiButtonSize', default: 'md', required: false },
      { name: 'type', type: 'button | submit | reset', default: 'button', required: false },
      { name: 'disabled', type: null, default: false, required: false },
      { name: 'loading', type: null, default: false, required: false },
      { name: 'full', type: null, default: false, required: false },
    ],
    outputs: [],
    component: ButtonComponent,
    demos: buttonDemo.demos,
  },
  {
    name: 'CardComponent',
    selector: 'ui-card',
    description: 'Dense card surface with optional header (title/subtitle), icon and action slots.',
    inputs: [
      { name: 'title', type: 'string', default: null, required: false },
      { name: 'subtitle', type: 'string', default: null, required: false },
      { name: 'padded', type: null, default: true, required: false },
    ],
    outputs: [],
    component: CardComponent,
    demos: cardDemo.demos,
  },
  {
    name: 'DialogComponent',
    selector: 'ui-dialog',
    description: 'Modal dialog with backdrop, Escape/backdrop close, glass or solid appearance and a footer slot.',
    inputs: [
      { name: 'appearance', type: 'UiDialogAppearance', default: 'glass', required: false },
      { name: 'title', type: 'string', default: null, required: false },
      { name: 'closeOnBackdrop', type: null, default: true, required: false },
      { name: 'closeOnEscape', type: null, default: true, required: false },
      { name: 'maxWidth', type: null, default: '500px', required: false },
      { name: 'open', type: null, default: false, required: false, twoWay: true },
    ],
    outputs: ['close'],
    component: DialogComponent,
    demos: dialogDemo.demos,
  },
  {
    name: 'FormFieldComponent',
    selector: 'ui-form-field',
    description: 'Label/hint/error wrapper around form controls.',
    inputs: [
      { name: 'label', type: 'string', default: null, required: false },
      { name: 'hint', type: 'string', default: null, required: false },
      { name: 'error', type: 'string', default: null, required: false },
    ],
    outputs: [],
    component: FormFieldComponent,
    demos: formFieldDemo.demos,
  },
  {
    name: 'InputComponent',
    selector: 'ui-input',
    description: 'Styled text input (ControlValueAccessor) supporting common input types.',
    inputs: [
      { name: 'type', type: 'UiInputType', default: 'text', required: false },
      { name: 'placeholder', type: 'string', default: null, required: false },
      { name: 'maxlength', type: 'number', default: null, required: false },
      { name: 'disabled', type: null, default: false, required: false },
      { name: 'invalid', type: null, default: false, required: false },
      { name: 'ariaLabel', type: 'string', default: null, required: false },
    ],
    outputs: [],
    component: InputComponent,
    demos: inputDemo.demos,
  },
  {
    name: 'ProgressComponent',
    selector: 'ui-progress',
    description: 'Thin progress bar with two sizes; the fill turns green at 100%.',
    inputs: [
      { name: 'value', type: null, default: 0, required: false },
      { name: 'max', type: null, default: 100, required: false },
      { name: 'size', type: 'sm | md', default: 'sm', required: false },
    ],
    outputs: [],
    component: ProgressComponent,
    demos: progressDemo.demos,
  },
  {
    name: 'SpinnerComponent',
    selector: 'ui-spinner',
    description: 'Loading spinner with size presets (or a custom pixel size) and accent/light variants.',
    inputs: [
      { name: 'size', type: 'UiSpinnerSize | number', default: 'md', required: false },
      { name: 'variant', type: 'UiSpinnerVariant', default: 'accent', required: false },
    ],
    outputs: [],
    component: SpinnerComponent,
    demos: spinnerDemo.demos,
  },
];
